update zshrc configuration file for macOS

diff --git a/zsh-config/zshrc_for_mac b/zsh-config/zshrc_for_mac
--- a/zsh-config/zshrc_for_mac
+++ b/zsh-config/zshrc_for_mac
@@ -13,6 +13,11 @@ PATH="/usr/local/Cellar/mongodb/3.6.2/bin:$PATH"
 PATH="/usr/local/sbin:$PATH"
 export PATH
 
+# for python virtualenvwrapper
+exportWORKON_HOME='~/.virtualenvs'    
+source /usr/local/bin/virtualenvwrapper.sh 
+
+
 # Set name of the theme to load. Optionally, if you set this to "random"
 # it'll load a random theme each time that oh-my-zsh is loaded.
 # See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
@@ -68,7 +73,7 @@ ZSH_THEME="robbyrussell"
 # Example format: plugins=(rails git textmate ruby lighthouse)
 # Add wisely, as too many plugins slow down shell startup.
 plugins=(
-  git
+git
 )
 
 source $ZSH/oh-my-zsh.sh
@@ -114,30 +119,33 @@ alias nvim_config="nvim ~/.config/nvim/init.vim"
 alias_hint='Welcome back Apolo, you have following shortcuts set-up: 
 
 alias:
-    godoc="cd ~/Documents"
-    mysql_run="mysql -u root -p"
-    django_run="python manage.py runserver 127.0.0.1:8080"
-    nvim_config="nvim ~/.config/nvim/init.vim"
-    px="proxychains4"
+godoc="cd ~/Documents"
+mysql_run="mysql -u root -p"
+django_run="python manage.py runserver 127.0.0.1:8080"
+nvim_config="nvim ~/.config/nvim/init.vim"
+px="proxychains4"
 ';
 echo $alias_hint 
 
 
-custom_function_hint="git:
-    gl => git log --oneline
-    gs => git status 
+custom_function_hint="bash:
+cdls => cd && ls
+git:
+gl => git log --oneline --graph
+gs => git status 
+init_ignore => create a pre-configured .gitignore
 
 tmux:
-    tls => tmux ls
-    tnew => tmux new -s
-    ta => tmux attach -t
-    td => tmux detach
-    tks => tmux kill-session -t
+tls => tmux ls
+tnew => tmux new -s
+ta => tmux attach -t
+td => tmux detach
+tks => tmux kill-session -t
 ";
 echo $custom_function_hint
 
 # alias for git
-alias gl="git log --oneline"
+alias gl="git log --oneline --graph"
 alias gs="git status"
 
 
@@ -162,49 +170,65 @@ export NVM_DIR="$HOME/.nvm"
 # customized function
 ## example: 
 myfunction(){
-    echo "$1"
+  echo "$1"
 }
-export myfunction
+
+## bash functions
+cdls(){
+  clear && cd "$1" 
+  if [ $? -eq 0 ] ; then 
+    ls 
+  else 
+    echo 'Please type a valid path'
+  fi
+}
+
+# copy .gitignore to current path
+init_ignore(){
+  cp ~/utils/.gitignore ./
+}
+
 
 ## tmux functions
 
 ### tmux ls
 tls(){
-    tmux ls
+  tmux ls
 }
+export tls
 
 ### tmux new -s
 tnew(){
-    if [ ! -z "$1" ]
-        then
-            tmux new -s "$1"
-    else
-        tmux new
-        echo "session name not set, default value will be used."
-    fi
+  if [ ! -z "$1" ]
+  then
+    tmux new -s "$1"
+  else
+    tmux new
+    echo "session name not set, default value will be used."
+  fi
 }
 export tnew
 
 ### tmux attach -t
 ta(){
-    tmux attach -t "$1"
+  tmux attach -t "$1"
 }
 export ta
 
 ### tmux detach
 td(){
-    tmux detach
+  tmux detach
 }
 export td
 
 ### tmux kill-session -t
 tks(){
-    if [ ! -z "$1" ]
-    then
-        tmux kill-session -t "$1"
-    else
-        echo "tmux kill-session failed due to tmux session-name not being set"
-    fi
+  if [ ! -z "$1" ]
+  then
+    tmux kill-session -t "$1"
+  else
+    echo "tmux kill-session failed due to tmux session-name not being set"
+  fi
 }
 export tks
 
